### PR TITLE
updated 404.html

### PR DESCRIPTION
**Pull request by NitinMadhukar**

### CODE REVIEW

**Review by kelvinkamau — COMMENTED** [review]
I do not understand what exact changes you made

**Comment by NitinMadhukar** [comment]
> I do not understand what exact changes you made

i have made an impressive error404  page

**Review by kelvinkamau — DISMISSED** [review]
@stellakaniaru could you please go through this...looks good to me

**Comment by stellakaniaru** [comment]
Hey @NitinMadhukar good job !
Could you make a few changes to give it the look and feel of the overall site? A few pointers on the same:
-Work on adding the DSC favicon
-Edit the title etc etc.

Basically, custom it to reflect the DSC look.

**Comment by NitinMadhukar** [comment]
> Hey @NitinMadhukar good job !
> Could you make a few changes to give it the look and feel of the overall site? A few pointers on the same:
> -Work on adding the DSC favicon
> -Edit the title etc etc.
> 
> Basically, custom it to reflect the DSC look.

yes i can

**Pull request closed without merging**
