### PR TITLE
Integrate gulp workflow

### PR DESCRIPTION
**Pull request by ashinzekene**
Minify html, css, javascript and compress images
live reload and simple server in development

@kelvinkamau  You would need to set up the project on https://travis-ci.com, so the minification and compression would occur once a pr is merged or a commit is made.
Travis would automatically run `npm run build` and the files would be available  in a `dist` folder

### CODE REVIEW

**Review by kelvinkamau — APPROVED** [review]

**Comment by ashinzekene** [comment]
Hi @kelvinkamau . Just want to know if you've configured travis or tested this

**Comment by kelvinkamau** [comment]
Hi @ashinzekene , I will configure travis this weekend. Had a busy week. Thanks for the PR.

**Comment by ashinzekene** [comment]
Alright. You're welcome

**Comment by kelvinkamau** [comment]
ATT @ashinzekene : Building is failing. I'm I doing anything wrong?
image

image

**Comment by ashinzekene** [comment]
Sorry rename the file to `.travis.yml`

**Comment by kelvinkamau** [comment]
Resolved! Working now...
image

**Comment by ashinzekene** [comment]
Congratulations! Feel free to message me if you have any issues

**Pull request merged**
