### PR TITLE
Team section redesign: have cards with circular image lead fixes #38

### LINKED ISSUE #38: complete redesign of team section to have cards with circular image lead
Proposed design  https://bootsnipp.com/snippets/xpyz9

### PR DESCRIPTION
**Pull request by stellakaniaru**
Went with having 3 cards per scroll view to reduce on scrolling.
deepinscreenshot_select-area_20190201144941

### CODE REVIEW

**Review by kelvinkamau — CHANGES_REQUESTED** [review]
I love the progess so far @stellakaniaru  🥇 . However I have a few recommendations to make 👍 

* I would recommend displaying all cards for the core team to appear all at once without the slider(carousel)

## Here is a snippet of what I am recommending for the next update
basic

**Comment by stellakaniaru** [comment]
On it.

**Comment by kelvinkamau** [comment]
@stellakaniaru Would you recommend a merge at this point or do you prefer to make a new PR rebuilding the cards from the ground up?

**Comment by stellakaniaru** [comment]
Perform the merge. I'll do a PR with the changes

**Comment by kelvinkamau** [comment]
Conflicting files
* Moving on to use [this carousel](https://bootsnipp.com/snippets/vlXl7)

**Pull request closed without merging**
